// <auto-generated />
using System;
using Clash.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clash.DataBase.Migrations.MemberList
{
    [DbContext(typeof(MemberListContext))]
    partial class MemberListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Clash.Domain.Entities.API.IconUrls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Medium");

                    b.Property<string>("Small");

                    b.Property<string>("Tiny");

                    b.HasKey("Id");

                    b.ToTable("IconUrls");
                });

            modelBuilder.Entity("Clash.Domain.Entities.API.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IconUrlsId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IconUrlsId");

                    b.ToTable("League");
                });

            modelBuilder.Entity("Clash.Domain.Entities.API.MemberList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClanRank")
                        .HasColumnName("CLAN_RANK");

                    b.Property<int>("Donation")
                        .HasColumnName("DONATION");

                    b.Property<int>("DonationsReceived")
                        .HasColumnName("DONATION_RECEIVED");

                    b.Property<int>("ExpLevel")
                        .HasColumnName("EXP");

                    b.Property<int?>("LeagueId");

                    b.Property<string>("Name")
                        .HasColumnName("NOME");

                    b.Property<int>("PreviousClanRank")
                        .HasColumnName("PREVIOUS_CLAN_RANK");

                    b.Property<string>("Role")
                        .HasColumnName("ROLE");

                    b.Property<string>("Tag")
                        .HasColumnName("TAG");

                    b.Property<int>("Trophies")
                        .HasColumnName("TROFEUS");

                    b.Property<int>("VersusTrophies")
                        .HasColumnName("VERSUS_TROFEUS");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("MemberList");
                });

            modelBuilder.Entity("Clash.Domain.Entities.API.League", b =>
                {
                    b.HasOne("Clash.Domain.Entities.API.IconUrls", "IconUrls")
                        .WithMany()
                        .HasForeignKey("IconUrlsId");
                });

            modelBuilder.Entity("Clash.Domain.Entities.API.MemberList", b =>
                {
                    b.HasOne("Clash.Domain.Entities.API.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId");
                });
#pragma warning restore 612, 618
        }
    }
}
